#!/usr/bin/env python

Import('env')

if (env["platform"] in ["x11"]):
    # Thirdparty source files
    thirdparty_dir = "#thirdparty/vulkan/"
    thirdparty_libdir = "#thirdparty/vulkan/lib"
    env.Append(CPPPATH=[thirdparty_dir], LIBPATH = [thirdparty_libdir])
    

# Godot source files
env.add_source_files(env.drivers_sources, "*.cpp")

Export('env')
