#!/usr/bin/env python

Import('env')
Import('env_modules')

env_spirv_cross = env_modules.Clone()

spirv_cross_dir = "#thirdparty/spirv-cross/"
spirv_cross_sources = [
#    "spirv_common.hpp",
#    "spirv.hpp",
#    "spirv_cross.hpp",
    "spirv_cross.cpp",
#    "spirv_cfg.hpp",
    "spirv_cfg.cpp",
]
spirv_cross_sources = [spirv_cross_dir + file for file in spirv_cross_sources]

env_spirv_cross.add_source_files(env.modules_sources, spirv_cross_sources)
env_spirv_cross.Append(CPPPATH=spirv_cross_dir)

env_spirv_cross.Append(CPPDEFINES = ['SPIRV_CROSS_EXCEPTIONS_TO_ASSERTIONS'])

# Godot's own source files
env_spirv_cross.add_source_files(env.modules_sources, "*.cpp")
